all:
	g++ parser_test.cpp Element.cpp Text.cpp String.cpp Parser.cpp Pool.cpp -o parser_test

debug:
	g++ parser_test.cpp Element.cpp Text.cpp String.cpp Parser.cpp Pool.cpp -g

profiler:
	g++ parser_test.cpp Element.cpp Text.cpp String.cpp Parser.cpp Pool.cpp -pg

clean:
	rm parser_test
